### PR TITLE
Add fast column/row label changes

### PR DESCRIPTION
**Pull request by jbeezley**
This addressed #157.  The client needs to be updated to handle the api change on `PUT /csv/:id/batch/label`.

### CODE REVIEW

**Comment by subdavis** [comment]
@jbeezley Would it be possible to return the new state of all rows and columns without any of the additional processing?  

[I referenced the issue here](https://github.com/girder/metabulo/issues/114#issuecomment-482208306), and I think the same conceptual problem still exists.

> There's a lot of server logic to be duplicated for operations like primary key change, such as what to change the row/column to that used to be the primary key. I'd rather not update the table view manually because any inconsistency between client and server could cause weird state sync problems.
> Given that, I'd propose a third option where PUT csv/id/lable/batch returns the new { rows: [], columns: [] } and none of the other fields so that the request doesn't do validation but label state is confined to the server. The table view can update quickly and run validation asynchronously.

**Comment by jbeezley** [comment]
Yeah, I just forgot that you had requested that before.

**Comment by subdavis** [comment]
Added changes that might work once the server response is modified.   I haven't tested them, and those commits are really more of a remote `git stash`.  They'll conflict with what I've done over @ #164, but this is less invasive and should merge first.

**Comment by jbeezley** [comment]
@subdavis It appears to work with the latest change.

**Pull request merged**
