### PR TITLE
Change Upload Behavior: error handling + immediate upload

### PR DESCRIPTION
**Pull request by subdavis**
Screenshot_20190624_140838

### CODE REVIEW

**Comment by subdavis** [comment]
Working on some more changes here FYI.

**Comment by subdavis** [comment]
## Delete confirmation

Screenshot_20190625_094209

## New upload screen.

Returning to this screen after upload will show all the currently available datasets.

Screenshot_20190625_094148

**Comment by subdavis** [comment]
> After I upload a file, I see a non-zero size listed while the file is being processed; upon completion, the size changes to read 0 B.

File size needs to be added to the rest API.  I can know its size at upload time, but when I query the server for a given dataset, that info is missing.  Should make this into a new issue.

> If a file has semantic issues (e.g., no primary key column), that fact is presented upon moving to the "view data" screen; would it be a good idea to present the problem in icon+popover form alongside the "processed successfully" badge?

I thought about that too.  I got into the weeds a bit, about showing a distillation of the parsing issues.  I suppose this could be boolean.  Either the file is perfect, or it needs cleanup in some way.  Anything more descriptive than this would probably make for clumsy UI.

I'll add this!

> Is the continue button necessary, now that the "view data" buttons are (1) easier to get to with the mouse and (2) take the user directly to the dataset they wish to see?

I believe it is, but could be wrong.  For new / unfamiliar users, I think a large part of this application's value is the guidance it provides.  I think we should raise this question at the meeting today.

**Comment by subdavis** [comment]
@waxlamp 

Screenshot_20190625_132350

**Comment by waxlamp** [comment]
Looks great!

**Pull request merged**
